name: general

on:
  push:
    paths:
      - 'index.md'
      - 'livemark.yaml'
      - 'pages/*.md'
      - 'blog/*.md'
      - 'build.sh'
      - 'Makefile'

jobs:

  # Update

  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install livemark
        run: pip install -r requirements.txt
      - name: Build html pages
        run:  make build
      - name: Commit build
        uses: stefanzweifel/git-auto-commit-action@v4
