name: general

on:
  push

jobs:

  # Update

  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install livemark
        run: pip install -r requirements.txt
      - name: Build html pages
        run: ./build.sh
      - name: Commit build
        uses: stefanzweifel/git-auto-commit-action@v4
